# Multi-species Dislocation Systems
Although much of the dislocation documentation uses single-species systems as case studies, the dislocation classes in `matscipy.dislocation` can also be applied to systems which have much more chemical complexity. However, the following restrictions apply:
1. The desired system can be expressed in a cubic lattice
2. The desired system shares on-lattice geometry with an existing "base" crystal structure

As an example, let's take Zincblende InP and compare with a diamond lattice:

In [1]:
import nglview # this import is necessary for rendering of the 3D view
import numpy as np
from ase.build import bulk
from ase.lattice.cubic import Diamond
from visualisation import interactive_view, show_dislocation

# Data from https://pubs.acs.org/doi/epdf/10.1021/acs.jpca.0c02450 DFT values
alat = 5.84
C11 = 99.3
C12 = 55.4
C44 = 45.0

InP = bulk("InP", crystalstructure="zincblende", cubic=True, a=alat)

diamond = Diamond("C", latticeconstant=alat)

inp_pos = InP.get_scaled_positions()
dia_pos = diamond.get_scaled_positions()

# Sort the coords, as bulk uses a different atom order
inp_idxs = np.lexsort((inp_pos[:, 0], inp_pos[:, 1], inp_pos[:, 2]))
dia_idxs = np.lexsort((dia_pos[:, 0], dia_pos[:, 1], dia_pos[:, 2]))
print("InP Fractional Coordinates")
print(inp_pos[inp_idxs, :])
print()
print("Diamond Fractional Coordinates")
print(dia_pos[dia_idxs, :])

interactive_view(InP, scale=0.4)

InP Fractional Coordinates
[[0.   0.   0.  ]
 [0.5  0.5  0.  ]
 [0.25 0.25 0.25]
 [0.75 0.75 0.25]
 [0.5  0.   0.5 ]
 [0.   0.5  0.5 ]
 [0.75 0.25 0.75]
 [0.25 0.75 0.75]]

Diamond Fractional Coordinates
[[0.   0.   0.  ]
 [0.5  0.5  0.  ]
 [0.25 0.25 0.25]
 [0.75 0.75 0.25]
 [0.5  0.   0.5 ]
 [0.   0.5  0.5 ]
 [0.75 0.25 0.75]
 [0.25 0.75 0.75]]


NGLWidget()

We can see that the fractional coordinates of the Zincblende InP are the same as the Diamond structure we generated. We can therefore say that on-lattice Zincblende shares geometry with Diamond. The displacement field used to generate dislocation structures is agnostic to atomic chemistry, and so we can model Zincblende dislocations as if they were dislocations in a Diamond crystal with an identical lattice constant and elastic properties.

To actually build a dislocation with this InP bulk, we can simply pass it as an argument in place of the lattice constant:

In [2]:
from matscipy.dislocation import DiamondGlide90degreePartial

disloc = DiamondGlide90degreePartial(InP, C11, C12, C44)

InP_bulk, InP_dislocation = disloc.build_cylinder(radius=3 * alat)

show_dislocation(InP_dislocation, scale=0.2, 
                 diamond_structure=True, 
                 CNA_color=False, add_bonds=True)

NGLWidget()

## Additional Dislocations in Multispecies Systems
Dislocations in multispecies systems have additiional complexity over thos in single-species crystals, due to the breaking of symmetries caused by the added chemical complexity. For our Zincblende InP example, this means that we can have two different forms of some of our dislocations: $\alpha$ (P-terminated), and $\beta$ (In-terminated).

$\alpha$-$90^\circ$ Partial Dislocation in InP:

In [8]:
# alpha-90 degree dislocation
InP = bulk("InP", crystalstructure="zincblende", cubic=True, a=alat)
symbols = np.array(InP.get_chemical_symbols())
# Swap In <-> P to get other alpha dislocation
new_symbols = symbols.copy()
new_symbols[symbols == "In"] = "P"
new_symbols[symbols == "P"] = "In"
InP.set_chemical_symbols(new_symbols)
disloc = DiamondGlide90degreePartial(InP, C11, C12, C44)

InP_bulk, InP_dislocation = disloc.build_cylinder(radius=3 * alat)
show_dislocation(InP_dislocation, scale=0.2, 
                 diamond_structure=True, d_name="alpha-90 degree partial",
                 CNA_color=False, add_bonds=True)

NGLWidget()

$\beta$-$90^\circ$ Partial Dislocation in InP:

In [4]:
InP = bulk("InP", crystalstructure="zincblende", cubic=True, a=alat)
# beta dislocation is the one done by default, for the bulk built by ase.build.bulk
disloc = DiamondGlide90degreePartial(InP, C11, C12, C44)

InP_bulk, InP_dislocation = disloc.build_cylinder(radius=3 * alat)
show_dislocation(InP_dislocation, scale=0.2, 
                 diamond_structure=True,
                 CNA_color=False, add_bonds=True)

NGLWidget()

## Dislocations in Disordered Systems
Generating dislocation structures for systems which have some chemical disorder is also possible, with some caveats:
1. The generation routines will only work reliably when given on-lattice bulk structures with cubic cells
2. The generated structure is based on a periodic replication of the base unit_cell, thus won't have true disorder
3. The displacement field applied to the bulk structure does not depend on atomic species - known lattice distortions caused by the disorder will not be captured
4. The current code only allows $C_{11}$, $C_{12}$, and $C_{44}$ to be specified, so more complex elastic effects (E.G. $C_{11} \neq C_{22}$) cannot currently be captured

With these in mind, a recommended workflow would be to start by generating the dislocation system for an ordered system, but using the elastic constants of the disordered system. From there, the disorder can be applied by simply changing the chemcical symbols of the atoms to match the target composition.

To show a worked example of this, consider the alloy $\text{In}_{0.5} \text{Ga}_{0.5} \text{As}$. This should form in a Zincblende structure, where the In sites from the previous InP bulk are now 50% occupied by Ga, and all P sites are now In.

In order to model this, we can generate a dislocation for GaAs (which is very similar to the InP example above), but using the lattice constant and elastic properties of $\text{In}_{0.5} \text{Ga}_{0.5} \text{As}$.

NOTE: Whilst disordered systems like this $\text{In}_{0.5} \text{Ga}_{0.5} \text{As}$ example should have off-lattice distortions in the bulk state, it is heavily recommended that the dislocation structures are generated using an on-lattice crystal. This is because the off-lattice structure will interact differently with the continuum displacement field, which could lead to overlapping/extremely close atoms, or generally incorrect core structures. The off-lattice distortions should ideally be found by relaxing the dislocation structure.

In [5]:
from ase.build import bulk
from matscipy.dislocation import DiamondGlide90degreePartial

alat = 5.87 # Rough value from https://www.ioffe.ru/SVA/NSM/Semicond/GaInAs/mechanic.html
# Data from https://doi.org/10.1080/08927022.2011.602975
C11 = 120.31
C12 = 55.87
C44 = 58.26

GaAs = bulk("GaAs", crystalstructure="zincblende", cubic=True, a=alat)


disloc = DiamondGlide90degreePartial(GaAs, C11, C12, C44)

GaAs_bulk, GaAs_dislocation = disloc.build_cylinder(radius=3 * alat)

show_dislocation(GaAs_dislocation, scale=0.2, 
                 diamond_structure=True,
                 CNA_color=False, add_bonds=True)

NGLWidget()

From this GaAs structure, we then do Monte Carlo sampling to introduce 50% Indium to the structure:

In [6]:
import numpy as np

np.random.seed(2)

species = np.array(GaAs_bulk.get_chemical_symbols())

Ga_idxs = np.argwhere(species == "Ga")[:, 0]

# Choose half the idxs to be In
In_idxs = np.random.choice(Ga_idxs, size=int(Ga_idxs.shape[0]/2), replace=False)

# Introduce the chemical disorder in In-Ga sites
species[In_idxs] = "In"

InGaAs_bulk = GaAs_bulk.copy()
InGaAs_bulk.set_chemical_symbols(species)

InGaAs_dislocation = GaAs_dislocation.copy()
InGaAs_dislocation.set_chemical_symbols(species)

view = show_dislocation(InGaAs_dislocation, scale=0.2,
                        diamond_structure=True,
                        CNA_color=False, add_bonds=True)

# In and Ga have almost the same default colors in nglview,
# so we add another component with the In atoms in red to
# see the chemical disorder better
c = view.add_component(nglview.ASEStructure(InGaAs_dislocation[In_idxs]), 
                                            default_representaion=False)
c.add_spacefill(radius=0.6, color="red")
view

NGLWidget()